---
baseURL: "https://chloebanks.co.uk/"
title: "Chloe Banks"
canonifyURLs: true
metaDataFormat: "yaml"
taxonomies:
  tag: "tags"
  series: "series"
params:
  DateForm: "2 January 2006"
paginate: 5
languageCode: en-gb
author:
  name: Chloe Banks
  email: hellochloe@chloebanks.co.uk
